language: generic
services:
- docker
script: |
  export RUST_DATE=$(date +"%Y-%m-%d")
  export RUST_CHANNEL="nightly-${RUST_DATE}"
  if [ "$TRAVIS_EVENT_TYPE" = "cron" ]; then
    echo "${DOCKER_PASSWORD}" | docker login -u="$DOCKER_USERNAME" --password-stdin
  fi
  set -e
  docker build --build-arg CHANNEL="${RUST_CHANNEL}" -t clux/muslrust .
  export RUST_VER=$(docker run -it clux/muslrust rustc --version | grep -oE "[[:digit:]]+\.[[:digit:]]+\.[[:digit:]]")
  export TAG1="${RUST_VER}-${RUST_CHANNEL}"
  export TAG2="nightly"
  export TAG3="${RUST_CHANNEL}"
  make test
after_success: |
  if [ "$TRAVIS_EVENT_TYPE" = "cron" ]; then
    docker push clux/muslrust
    docker tag clux/muslrust clux/muslrust:$TAG1
    docker push clux/muslrust:$TAG1
    docker tag clux/muslrust clux/muslrust:$TAG2
    docker push clux/muslrust:$TAG2
    docker tag clux/muslrust clux/muslrust:$TAG3
    docker push clux/muslrust:$TAG3
  fi
notifications:
  email:
    on_success: change
    on_failure: always
env:
  global:
    secure: nXeXIF1Ys/rMMyjSlpUR4u5JLZRYBe3rG6ES7UeuQxEH92fZoNu2nK/NSbPF/5ggm8nsf5TSJequXQY8yCsr+ipsUtMkbbYkIMmMWphNVvA2b+HG0QQHkh3b8hwzFAI1q6/WRpP7X9+y0mCc8OpSMNLV5Wi80MzNyZLG3cOmHFzoCGrFprB2R0kTuzaWQuedkl7/O6xnZRIWuZ8PRgkmJENVL+vjx5TaQegs+jScVPE8uaubBZktWmNTHpCB31cVsi0psoZNsv7bmO3JQ76ozRP+OLGb+dbdu69UFKd97WDAr02U+aiCfJxNbeqOm1Vhz1GiByy7D+RKjQPgkbt0ipfPx/vN83bM8aoLzyrNd4Zt4BIsLfj7pdApjH2+nn24V4Lo6NrOFFpQxrmoycZPomfG7mMlqQVxqtPhEnZKHW53yuUG6BEhKy2y497ctEWIZkJdZISNdAewkuhBvsR4nALoTBNz13S0ALsLvD+HBLDqMwfy6VRxzDJB++TqAldbSpjJmKOHxjDDaNfldQeQFOibo2/CN18oFRtLXA2K0w//Hp974yVwMBnMqtzx2UiKsxmlDDq3fafQTZv0WARCZa91llUwC/C3KTyZiW5wP4Gvn1Ze2ktg47MWEhzBpSOd64YiT2f1XkYklffb9NSTsupdHvYOX4JT9tAePjMKIeI=
branches:
  only:
    - master
